print("##############################")
print("#                            #")
print("#   Hari Octavian Delrossi   #")
print("#       2210817210033        #")
print("#                            #")
print("##############################")